"""
Practical task
Write a program that will calculate the sum, difference, product, exponentiation etc. of two numbers a and b that the program reads from the console (data entered by the user) and will output appropriate result:
"a + b = "  ...
"a - b = "   ...
"a * b = "   ...
"a / b = "   ...
"a**b = "   ...
"a//b = "   ...
"a%b = "  ... 
"""

a = float(input("Enter the first number: "))
b = float(input("Enter the second number: "))

print(f"{a} + {b} = {a + b}")
print(f"{a} - {b} = {a - b}")
print(f"{a} * {b} = {a * b}")
print(f"{a} / {b} = {a / b}")
print(f"{a} ** {b} = {a ** b}")
print(f"{a} // {b} = {a // b}")
print(f"{a} % {b} = {a % b}")